name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'  # Actualiza a Node.js 20

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        node-version: '20'  # Actualiza a Node.js 20

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Test with Maven
      run: ./mvnw test

