name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.23+9'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Persist target directory
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target/
        
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.23+9'
          distribution: 'adopt'

      - name: Test with Maven
        run: |
          chmod -R 700 *
          java -version
          pwd
          echo $JAVA_HOME
          mvn -N io.takari:maven:wrapper
          ./mvnw verify

  store:
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get target directory
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: target/

      - name: store jar artifact in guthub
        uses: actions/upload-artifact@v3
        with:
          name: unit-vs-int-0.0.1-SNAPSHOT.jar
          path: target/unit-vs-int-0.0.1-SNAPSHOT.jar


  deploy:
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest
    needs: store
    steps:
      - name: deploy jar in apache tomcat
        run: echo "Se deployo Jar en produccion"

      - name: Deploy to Apache Maven
        run: mvn deploy:deploy-file -Durl=https://maven.pkg.github.com/AldoNovas/api-codigo \
             -Dfile=target/unit-vs-int-0.0.1-SNAPSHOT.jar \
             -DgroupId=danvega.dev \
             -DartifactId=unit-vs-int \
             -Dversion=0.0.1-SNAPSHOT \
             -Dpackaging=jar \
             -DrepositoryId=github \
             -DrepositoryLayout=default \
             -DuniqueVersion=false \
             -DgeneratePom=true \
             -DupdateReleaseInfo=true
        env:
          TOKEN_API_GH: ${{ secrets.TOKEN_API_GH }}  # Aquí usas tu token de GitHub como secret
            
