name: Java CI/CD with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Agrega 'distribution' como se requiere

      - name: Build with Maven
        run: mvn clean install

      - name: Persist target directory
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Agrega 'distribution' como se requiere

      - name: Test with Maven
        run: |
          chmod -R 700 *
          java -version
          pwd
          echo $JAVA_HOME
          mvn -N io.takari:maven:wrapper
          ./mvnw verify

  store:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get target directory
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: target/

      - name: Store JAR artifact in GitHub
        uses: actions/upload-artifact@v3
        with:
          name: unit-vs-int-0.0.1-SNAPSHOT.jar
          path: target/unit-vs-int-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: store
    if: github.event_name == 'push'

    steps:
      - name: Deploy to Apache Maven
    run: pwd
  run: ls -l
run: 
            cd target 
            mvn deploy:deploy-file \
            -Durl=https://maven.pkg.github.com/AldoNovas/api-codigo \
            -Dfile=unit-vs-int-0.0.1-SNAPSHOT.jar \
            -DgroupId=danvega.dev \
            -DartifactId=unit-vs-int \
            -Dversion=0.0.1-SNAPSHOT \
            -Dpackaging=jar \
            -DrepositoryId=github \
            -DrepositoryLayout=default \
            -DuniqueVersion=false \
            -DgeneratePom=true \
            -DupdateReleaseInfo=true
        env:
          TOKEN_API_GH: ${{ secrets.TOKEN_API_GH }}

      - name: Deploy JAR to Apache Tomcat
        run: echo "Se deployó el JAR en producción"
