name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.23+9'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Persist target directory
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target/
        
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.23+9'
          distribution: 'adopt'

      - name: Test with Maven
        run: |
          chmod -R 700 *
          java -version
          pwd
          echo $JAVA_HOME
          mvn -N io.takari:maven:wrapper
          ./mvnw verify

  store:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get target directory
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: target/

      - name: Set up token
        env:
          TOKEN_API_GH: ${{ secrets.TOKEN_API_GH }}
        uses: actions/download-artifact@v2

      - name: Upload to GitHub Packages
        run: |
          JAR_FILE=$(find target -name '*.jar')
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          mvn deploy:deploy-file \
            -Dfile=$JAR_FILE \
            -Durl=https://maven.pkg.github.com/AldoNovas/api-codigo \
            -DrepositoryId=github \
            -DaccessToken=$TOKEN_API_GH
